version: '3.1'

services:
  mq:
    image: rmohr/activemq:5.15.9
    ports:
      - 61616:61616
      - 8161:8161
      - 5672:5672

  db:
    image: mysql:5.7.33
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: odp
      MYSQL_USER: odpu
      MYSQL_PASSWORD: odpp
    ports:
    - 3306:3306